version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ddcattle_company_db
      POSTGRES_USER: dduser
      POSTGRES_PASSWORD: Thebigdawgisawesome!
    volumes:
      - ddcattle_company_db_data:/var/lib/postgresql/data
    ports:
      - "6543:5432"  # Change the host port to 6543

  web:
    build: .
    ports:
      - "3002:3002"
    volumes:
      - .:/usr/src/app
      - media_data:/usr/src/app/uploads
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://dduser:Thebigdawgisawesome!@db:5432/ddcattle_company_db  # Use internal port 5432
      - EMAIL_ENCRYPTION_KEY=kaj!!oifasgk5648nasd8945987L2165
      - EMAIL_ENCRYPTION_IV=RandomInitVector
      - JWT_SECRET=lakflk&*lkasjdf56643
      - NODE_ENV=development

volumes:
  ddcattle_company_db_data: 
  media_data:


