INSERT INTO "public"."horses" ("id", "name", "breed", "color", "sex", "foal_year", "brand", "HMA", "description", "deceased", "off_property_rides", "createdAt", "updatedAt")
VALUES
('2db88c9c-f44b-ebb8-3aa8-8a1d494f68c0', 'Sioux', 'Mustang', 'Gray', 'MARE', '2005', '05839350', 'Sweet Water, Wyoming', '', null, 'false', CURRENT_DATE, CURRENT_DATE),
('4d8df2dd-17dd-4ab3-8618-8d567b8ced6b', 'Titus', 'Mustang', 'Red Roan', 'GELDING', '2021', '21027061', 'Stinking Water, Oregon', 'Titus is a very confident horse. He''s curious, which can get him into trouble at times. He has a one-of-a-kind personality that likes to please but also likes to test the boundaries of his rider. He''s a great trail horse, but he has no problem leaving the trail to find another adventure. Sometimes he may see a deer trail and just decide he wants to go down it. It is a blast working with him each day!', null, 'true', CURRENT_DATE, CURRENT_DATE),
('5ac7f789-f777-48a7-97a2-32f25221edf8', 'Dancer', 'Mustang', 'Bay', 'GELDING', '2004', null, null, '', null, 'false', CURRENT_DATE, CURRENT_DATE),
('64ba8953-f9bf-0d76-cd52-5285808ac305', 'Ty', 'Mustang', 'Red Dun', 'GELDING', '2004', '04591559', 'Antelope Valley, Nevada', 'Ty is a shy and timid horse. He likes his space but once he is caught is a super sweet guy.', null, 'false', CURRENT_DATE, CURRENT_DATE),
('8ae3239c-7ab4-5dae-b11a-2143a187fcbd', 'Jett', 'Mustang', 'Black', 'MARE', '2007', null, null, 'Jet was born on the property in 2007. She is a sweet girl that loves attention. She has potential to be a lead mare despite her small size.', null, 'false', CURRENT_DATE, CURRENT_DATE),
('8e9848b7-b4c6-38cb-eaec-b6ac2e6a96cf', 'Star', 'Quarter Horse', 'Bay', 'GELDING', '2011', null, null, 'Star just completed his 90-day training session. He learned some much-needed manners, and we even got a few rides out of him. We''re so proud of him!', null, 'false', CURRENT_DATE, CURRENT_DATE),
('97b96d99-d250-49fb-bf79-cf277ede3b36', 'Henry', 'Mustang', 'Dunn', 'GELDING', '2021', null, 'Palimino Butte, Oregon', 'Henry is a sweet, gentle horse that we got from Palimino Butte, Oregon. He has grown and developed beyond our expectations. We think he''s an awesome trail horse. He is a joy to ride and his sweet, gentle nature makes him a pleasure to be around. He is a good listener and a willing partner on the trail.', null, 'true', CURRENT_DATE, CURRENT_DATE),
('a95d70af-d5a8-35c5-e82b-838665c53654', 'Reno', 'Mustang', 'Palomino', 'GELDING', '2000', '00833823', 'Dads Reservoir, Wyoming', 'Reno is a big boy. He is a smooth ride in the round pen, but a little unpredictable on the trail. ', null, 'false', CURRENT_DATE, CURRENT_DATE),
('bc0bf059-33b6-48ef-ba77-be4c9f975ccc', 'Tidd Bit', 'Halflinger', 'Chestnut', 'GELDING', '2020', null, null, 'Tidd bit is an awesome little guy. He can be a bit stubborn but he loves to be outfront and leading the way.', null, 'false', CURRENT_DATE, CURRENT_DATE),
('c8936d47-7b9f-dd1e-e1d7-ca4aa0c24d24', 'Desiree', 'Mustang', 'Bay Roan', 'MARE', '1999', '99834654', 'Sweet Water, Wyoming', '', null, 'false', CURRENT_DATE, CURRENT_DATE),
('e132ab75-1d1b-8917-ac50-296e92769fbc', 'Amigo', 'Paint', 'Brown/White', 'GELDING', '2000', null, null, 'Amigo was a sweet horse who was with David since he was a yearling. He had a long life of trail rides and love. He was laid to rest in July of 2024 after a long happy life. He will be missed.', '2024-07-29', 'false', CURRENT_DATE, CURRENT_DATE),
('e453bda8-7939-b388-3944-d50079279f61', 'Siera', 'Mustang', 'Gray', 'MARE', '2001', '1576769', 'Elko, Nevado', '', null, 'false', CURRENT_DATE, CURRENT_DATE),
('e744a2af-a4d1-a993-ee8e-d374babcc360', 'Pedro', 'Burro', 'Gray', 'GELDING', '1992', null, null, 'Pedro is our little burro. He is absolutely in love with his lady, Sioux. ', null, 'false', CURRENT_DATE, CURRENT_DATE);